// Inside exams/test1.js
EXAM_DATA = {
  title: "Blood and Circulation - 1",
  durationMinutes: 60,
  questions: [
    {
      id: 1,
      text: "What percentage of total body weight does blood account for in a healthy adult?",
      options: ["5%", "6%", "8%", "10%"],
      correctOptionIndex: 2,
    },
    {
      id: 2,
      text: "What is the chemical nature of human blood?",
      options: [
        "Slightly acidic",
        "Strongly acidic",
        "Slightly alkaline",
        "Strongly alkaline",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 3,
      text: "What is the average pH of human blood?",
      options: ["7.35", "7.40", "7.45", "7.50"],
      correctOptionIndex: 1,
    },
    {
      id: 4,
      text: "What is the normal temperature range of human blood?",
      options: ["34-36°C", "36-38°C", "37-39°C", "38-40°C"],
      correctOptionIndex: 1,
    },
    {
      id: 5,
      text: "What is the approximate specific gravity of whole blood?",
      options: ["1.025", "1.045", "1.065", "1.085"],
      correctOptionIndex: 2,
    },
    {
      id: 6,
      text: "The salty taste of blood is primarily due to:",
      options: [
        "Plasma proteins",
        "Organic acids",
        "Inorganic salts",
        "Essential electrolytes",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 7,
      text: "How does blood viscosity compare to pure water?",
      options: [
        "It is approximately equal",
        "It is about 3 times higher",
        "It is about 5 times higher",
        "It is about 8 times higher",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 8,
      text: "Which components primarily cause the higher viscosity of blood?",
      options: [
        "White blood cells and platelets",
        "Red blood cells and plasma proteins",
        "Inorganic salts and water",
        "Hormones and immune cells",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 9,
      text: "Which blood components primarily transport respiratory gases?",
      options: [
        "Leukocytes and plasma",
        "Erythrocytes and plasma",
        "Platelets and erythrocytes",
        "Plasma proteins and leukocytes",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 10,
      text: "Which metabolic waste product is transported by the blood for excretion?",
      options: ["Glycerol", "Amino acids", "Bilirubin", "Glycogen"],
      correctOptionIndex: 2,
    },
    {
      id: 11,
      text: "How does blood primarily reduce high body temperature?",
      options: [
        "By decreasing circulation to the skin",
        "By diverting blood flow to the body's periphery",
        "By increasing heat production in the liver",
        "By absorbing excess water from the kidneys",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 12,
      text: "Through which mechanisms do white blood cells defend against pathogens?",
      options: [
        "Coagulation and agglutination",
        "Osmosis and active transport",
        "Phagocytosis and antibody production",
        "Hemostasis and buffering",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 13,
      text: "During fasting, which blood component serves as a reserve protein source?",
      options: ["Erythrocytes", "Plasma proteins", "Amino acids", "Leukocytes"],
      correctOptionIndex: 1,
    },
    {
      id: 14,
      text: "Where are the primary buffers that maintain the body's acid-base balance located?",
      options: [
        "Blood plasma only",
        "Plasma and white blood cells",
        "Red blood cells and platelets",
        "Plasma and red blood cells",
      ],
      correctOptionIndex: 3,
    },
    {
      id: 15,
      text: "Which two components work together to cause blood coagulation?",
      options: [
        "Platelets and red blood cells",
        "Platelets and white blood cells",
        "Platelets and plasma proteins",
        "Red blood cells and plasma proteins",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 16,
      text: "What is the role of blood in maintaining a stable internal environment called?",
      options: ["Hemostasis", "Homeostasis", "Hematopoiesis", "Hemolysis"],
      correctOptionIndex: 1,
    },
    {
      id: 17,
      text: "What percentage of organic constituents in blood plasma are plasma proteins?",
      options: ["1.5%", "7.5%", "8.0%", "9.5%"],
      correctOptionIndex: 1,
    },
    {
      id: 18,
      text: "Which is classified as a nitrogenous excretory product in the blood?",
      options: ["Bilirubin", "Cholesterol", "Xanthine", "Carotene"],
      correctOptionIndex: 2,
    },
    {
      id: 19,
      text: "Which pigment is found in blood plasma?",
      options: ["Hemoglobin", "Melanin", "Carotene", "Rhodopsin"],
      correctOptionIndex: 2,
    },
    {
      id: 20,
      text: "In what primary form is carbon dioxide transported in blood plasma?",
      options: [
        "As dissolved $\\ce{CO2}$ gas",
        "As carbonic acid",
        "As carbaminohemoglobin",
        "As bicarbonate",
      ],
      correctOptionIndex: 3,
    },
    {
      id: 21,
      text: "What percentage of total blood volume is occupied by red blood cells?",
      options: ["1%", "44%", "45%", "55%"],
      correctOptionIndex: 1,
    },
    {
      id: 22,
      text: "Which is a direct function of blood plasma?",
      options: [
        "Performing phagocytosis to destroy pathogens",
        "Transporting the absolute majority of oxygen to tissues",
        "Maintaining the acid-base balance of the blood",
        "Generating heat energy during muscle contraction",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 23,
      text: "The transport of essential blood coagulation components is primarily carried by:",
      options: [
        "Blood plasma",
        "Platelets directly",
        "Erythrocytes",
        "Leukocytes",
      ],
      correctOptionIndex: 0,
    },
    {
      id: 24,
      text: "Before oxygen binds to red blood cells, what must initially occur?",
      options: [
        "It must react with plasma enzymes",
        "It must bind to transport proteins like albumin",
        "It must dissolve directly into the blood plasma",
        "It must be converted into a bicarbonate ion",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 25,
      text: "What is the characteristic shape of a mature human red blood cell?",
      options: [
        "Biconvex and nucleated",
        "Spherical and non-nucleated",
        "Biconcave and non-nucleated",
        "Flattened and multi-nucleated",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 26,
      text: "What is the average thickness at the center of a human erythrocyte?",
      options: ["1.0 μm", "2.2 μm", "7.3 μm", "9.0 μm"],
      correctOptionIndex: 0,
    },
    {
      id: 27,
      text: "What is the normal range of red blood cells per cubic millimeter in a fetus?",
      options: [
        "4.4 - 4.9 million",
        "5.0 - 5.4 million",
        "6.0 - 7.0 million",
        "8.0 - 9.0 million",
      ],
      correctOptionIndex: 3,
    },
    {
      id: 28,
      text: "A normal red blood cell count of 4.4 to 4.9 million per cubic millimeter is characteristic of:",
      options: ["Children", "Adult females", "Adult males", "Fetuses"],
      correctOptionIndex: 1,
    },
    {
      id: 29,
      text: "When does the red blood cell count naturally increase?",
      options: [
        "During sleep and digestion",
        "During fasting and dehydration",
        "During exercise and pregnancy",
        "During rest and low altitudes",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 30,
      text: "What is the average lifespan of a human red blood cell?",
      options: ["90 days", "100 days", "120 days", "150 days"],
      correctOptionIndex: 2,
    },
    {
      id: 31,
      text: "Red blood cells are primarily produced from stem cells in the:",
      options: ["Kidneys", "Yellow bone marrow", "Spleen", "Red bone marrow"],
      correctOptionIndex: 3,
    },
    {
      id: 32,
      text: "Which hormone do the kidneys secrete to stimulate red blood cell production?",
      options: ["Hemoglobin", "Erythropoietin", "Thyroxine", "Adrenaline"],
      correctOptionIndex: 1,
    },
    {
      id: 33,
      text: "What is a primary trigger for increased erythropoietin secretion?",
      options: [
        "Staying at low altitudes",
        "High oxygen levels in tissues",
        "Excessive hemoglobin production",
        "Hemorrhage or blood loss",
      ],
      correctOptionIndex: 3,
    },
    {
      id: 34,
      text: "A hemoglobin molecule is composed of which two primary constituents?",
      options: [
        "A copper-containing pigment (heme) and a globulin protein",
        "An iron-containing protein (heme) and a carbohydrate (globin)",
        "An iron-containing pigment (heme) and a protein (globin)",
        "A heme protein and a globin pigment",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 35,
      text: "What is the normal reference range for hemoglobin in an adult female?",
      options: [
        "10.5 - 14.5 gm/dL",
        "11.5 - 15.5 gm/dL",
        "12.5 - 16.5 gm/dL",
        "13.5 - 17.5 gm/dL",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 36,
      text: "Which red blood cell component determines a person's blood group?",
      options: [
        "The specific type of hemoglobin in the cytoplasm",
        "The unique combination of intracellular buffers",
        "Antigen proteins attached to the plasma membrane",
        "Bilirubin and biliverdin concentrations on the cell surface",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 37,
      text: "What is the physiological role of the hydrogen sulfide gas produced by red blood cells?",
      options: [
        "It acts as an enzyme similar to L-arginine",
        "It triggers the production of nitric oxide",
        "It signals for the constriction of blood vessels",
        "It maintains the overall density and viscosity of blood",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 38,
      text: "Which compound produced by red blood cells acts similarly to L-arginine for endothelial cells?",
      options: [
        "Hydrogen sulfide",
        "Nitric oxide",
        "Biliverdin",
        "Bicarbonate",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 39,
      text: "Which accurately describes a mature human white blood cell?",
      options: [
        "Spherical in shape, lacks a nucleus, and contains hemoglobin.",
        "Irregularly shaped, nucleated, and lacks hemoglobin.",
        "Fixed shape, lacks a nucleus, and is colorless.",
        "Biconcave, nucleated, and contains pigment.",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 40,
      text: "What is the average white blood cell count per cubic millimeter in a healthy human?",
      options: ["4,000", "7,500", "11,000", "15,000"],
      correctOptionIndex: 1,
    },
    {
      id: 41,
      text: "What is the approximate ratio of RBCs to WBCs in the human body?",
      options: ["1 : 600", "600 : 1", "1 : 7500", "7500 : 1"],
      correctOptionIndex: 1,
    },
    {
      id: 42,
      text: "Which statement comparing red and white blood cells is correct?",
      options: [
        "White blood cells are generally larger than red blood cells.",
        "Red blood cells are generally larger than white blood cells.",
        "Both types of cells are identical in size but differ in shape.",
        "White blood cells decrease in size when a person is sick, while red blood cells grow.",
      ],
      correctOptionIndex: 0,
    },
    {
      id: 43,
      text: "What is the medical term for an abnormally low white blood cell count?",
      options: ["Leukocytosis", "Leukemia", "Leukopenia", "Phagocytosis"],
      correctOptionIndex: 2,
    },
    {
      id: 44,
      text: "What are the two primary classifications of white blood cells?",
      options: [
        "Erythrocytes and Leucocytes",
        "Lymphocytes and Monocytes",
        "Agranulocytes and Granulocytes",
        "Phagocytes and Macrophages",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 45,
      text: "What shape does an aging monocyte's nucleus typically assume?",
      options: [
        "Unlobed and completely spherical",
        "Horseshoe or kidney-shaped",
        "Fragmented into multiple distinct lobes",
        "Elongated and rod-like",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 46,
      text: "What is the average lifespan of a monocyte?",
      options: [
        "2 to 5 days",
        "Exactly 7 days",
        "12 to 20 days",
        "20 to 40 days",
      ],
      correctOptionIndex: 0,
    },
    {
      id: 47,
      text: "What is the typical diameter of a monocyte?",
      options: [
        "2 to 8 micrometers",
        "6 to 16 micrometers",
        "12 to 20 micrometers",
        "20 to 40 micrometers",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 48,
      text: "What percentage of total white blood cells are lymphocytes?",
      options: ["2-8%", "6-16%", "20-40%", "60-80%"],
      correctOptionIndex: 2,
    },
    {
      id: 49,
      text: "Which best describes the cytoplasm of a lymphocyte?",
      options: [
        "Abundant, granular, and acidic",
        "Clear, agranular, and basophilic (alkaline-loving)",
        "Scanty, granular, and neutral",
        "Clear, agranular, and highly acidic",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 50,
      text: "What is the primary structural characteristic of a lymphocyte's nucleus?",
      options: [
        "Small and kidney-shaped",
        "Large, round, and unlobed",
        "Multi-lobed and irregular",
        "Horseshoe-shaped and positioned at the edge",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 51,
      text: "Where do T lymphocytes originate?",
      options: [
        "Hematopoietic stem cells in the bone marrow",
        "Thymocytes in the thymus gland",
        "Phagocytes in the bloodstream",
        "Natural killer cells in the lymphatic system",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 52,
      text: "Which type of immunity depends primarily on B lymphocytes?",
      options: [
        "Cell-mediated immunity",
        "Humoral immunity",
        "Phagocytic immunity",
        "Innate immunity",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 53,
      text: "Which threat triggers the most rapid response from Natural Killer cells?",
      options: [
        "Bacterial infections",
        "Fungal spores",
        "Parasitic worms",
        "Viral infections",
      ],
      correctOptionIndex: 3,
    },
    {
      id: 54,
      text: "Unlike monocytes, which process do lymphocytes NOT perform?",
      options: [
        "Cell division",
        "Phagocytosis",
        "Humoral immunity",
        "Cell-mediated immunity",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 55,
      text: "Which dye is used for staining the granules of granulocytes?",
      options: [
        "Eosin stain",
        "Leishman stain",
        "Iodine stain",
        "Hematoxylin stain",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 56,
      text: "What percentage of circulating blood are neutrophils?",
      options: ["2-4%", "20-40%", "40-60%", "60-80%"],
      correctOptionIndex: 2,
    },
    {
      id: 57,
      text: "How many lobes does a typical neutrophil nucleus contain?",
      options: ["1 to 2", "2 to 3", "2 to 5", "4 to 6"],
      correctOptionIndex: 2,
    },
    {
      id: 58,
      text: "What is the definition of 'diapedesis' for white blood cells?",
      options: [
        "The engulfing of bacteria by amoeboid movement",
        "The production of antibodies against pathogens",
        "The secretion of histamine to trigger inflammation",
        "The squeezing of cells through capillary walls into tissues",
      ],
      correctOptionIndex: 3,
    },
    {
      id: 59,
      text: "What color do eosinophil granules exhibit after taking up eosin dye?",
      options: ["Blue", "Red", "Purple", "Colorless"],
      correctOptionIndex: 1,
    },
    {
      id: 60,
      text: "An increase in eosinophils is most strongly associated with which condition?",
      options: [
        "Viral infections",
        "Parasitic infections",
        "Bacterial pneumonia",
        "Internal bleeding",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 61,
      text: "Which leukocyte makes up the smallest fraction of total white blood cells?",
      options: ["Monocyte", "Eosinophil", "Basophil", "Lymphocyte"],
      correctOptionIndex: 2,
    },
    {
      id: 62,
      text: "Which substance secreted by basophils prevents intravascular blood clotting?",
      options: ["Histamine", "Heparin", "Fibrinogen", "Prothrombin"],
      correctOptionIndex: 1,
    },
    {
      id: 63,
      text: "What is the average lifespan of a basophil?",
      options: ["2-5 days", "7-10 days", "8-12 days", "12-15 days"],
      correctOptionIndex: 3,
    },
    {
      id: 64,
      text: "Which two types of white blood cells primarily perform phagocytosis?",
      options: [
        "Lymphocytes and Basophils",
        "Monocytes and Neutrophils",
        "Eosinophils and Monocytes",
        "Neutrophils and Lymphocytes",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 65,
      text: 'Which cells are sometimes called "microscopic soldiers" because they produce antibodies?',
      options: ["Lymphocytes", "Eosinophils", "Macrophages", "Neutrophils"],
      correctOptionIndex: 0,
    },
    {
      id: 66,
      text: "From which giant cells in the red bone marrow do platelets originate?",
      options: ["Macrophages", "Erythroblasts", "Megakaryocytes", "Thymocytes"],
      correctOptionIndex: 2,
    },
    {
      id: 67,
      text: "What is the standard range of platelets per cubic millimeter of human blood?",
      options: [
        "50,000 to 100,000",
        "150,000 to 400,000",
        "400,000 to 600,000",
        "1,500,000 to 4,000,000",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 68,
      text: "What is the typical lifespan of a platelet in the bloodstream?",
      options: ["1 to 4 days", "5 to 9 days", "10 to 14 days", "15 to 20 days"],
      correctOptionIndex: 1,
    },
    {
      id: 69,
      text: "Where are aging or dead platelets primarily destroyed?",
      options: [
        "Macrophages of the liver and spleen",
        "Endothelium of the blood vessels",
        "Red bone marrow and thymus",
        "Kidneys and pancreas",
      ],
      correctOptionIndex: 0,
    },
    {
      id: 70,
      text: "Which substance is released from the platelet membrane to accelerate blood clotting?",
      options: ["Glycoprotein", "Phospholipid", "Cholesterol", "Heparin"],
      correctOptionIndex: 1,
    },
    {
      id: 71,
      text: "Which chemical is secreted by platelets to induce rapid blood vessel contraction?",
      options: ["Histamine", "Heparin", "Serotonin", "Melatonin"],
      correctOptionIndex: 2,
    },
    {
      id: 72,
      text: "Platelets secrete which of the following to protect the blood vessel endothelium?",
      options: [
        "Clotting factors",
        "Growth factors",
        "Specific antibodies",
        "Macrophages",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 73,
      text: "An abnormally high platelet count significantly increases the risk of:",
      options: [
        "Hemophilia and internal bleeding",
        "Severe allergic reactions",
        "Stroke and heart attack",
        "Decreased blood viscosity",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 74,
      text: "Where are red blood cells primarily produced during the fetal stage?",
      options: [
        "Red bone marrow",
        "Liver and spleen",
        "Lymph nodes and thymus",
        "Yellow bone marrow",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 75,
      text: "What is the standard red blood cell count per cubic millimeter in an adult female?",
      options: [
        "4 million (40 Lakh)",
        "4.5 million (45 Lakh)",
        "5 million (50 Lakh)",
        "5.5 million (55 Lakh)",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 76,
      text: "Which organs act as source sites for both monocytes and lymphocytes, besides red bone marrow?",
      options: [
        "Liver and kidneys",
        "Thymus and thyroid",
        "Spleen and lymph nodes",
        "Gallbladder and pancreas",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 77,
      text: "Which leukocyte has the lowest normal count per cubic millimeter?",
      options: ["Eosinophil", "Basophil", "Monocyte", "Neutrophil"],
      correctOptionIndex: 1,
    },
    {
      id: 78,
      text: "What is the exclusive production site for neutrophils, eosinophils, basophils, and platelets?",
      options: ["Spleen", "Lymph nodes", "Liver", "Red bone marrow"],
      correctOptionIndex: 3,
    },
    {
      id: 79,
      text: "What is the standard normal range for platelets per cubic millimeter of blood?",
      options: [
        "100,000 to 200,000 (1-2 Lakh)",
        "150,000 to 400,000 (1.5-4 Lakh)",
        "400,000 to 500,000 (4-5 Lakh)",
        "4.5 million to 5 million (45-50 Lakh)",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 80,
      text: "Which combination primarily prevents blood from clotting inside undamaged blood vessels?",
      options: [
        "Continuous prothrombin synthesis and active platelets",
        "Circulation of a mucopolysaccharide called heparin and smooth inner walls",
        "Absence of the thirteen distinct clotting factors in the blood plasma",
        "The constant circulation of fibrinogen and lack of calcium ions",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 81,
      text: "Which correctly identifies the four most critical clotting factors?",
      options: [
        "Fibrin, Thrombin, Thromboplastin, $\\ce{Ca^2+}$",
        "Fibrinogen, Prothrombin, Thromboplastin, $\\ce{K^+}$",
        "Fibrinogen, Thrombin, Thrombokinase, $\\ce{Ca^2+}$",
        "Fibrinogen, Prothrombin, Thromboplastin, $\\ce{Ca^2+}$",
      ],
      correctOptionIndex: 3,
    },
    {
      id: 82,
      text: "Where is Factor II (Prothrombin) synthesized, and what is essential for it?",
      options: [
        "Bone marrow; Vitamin K",
        "Liver; Vitamin C",
        "Liver; Vitamin K",
        "Spleen; Calcium ions",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 83,
      text: "Factor I (Fibrinogen) belongs to which category of proteins?",
      options: ["Albumin", "Globulin", "Lipoprotein", "Glycoprotein"],
      correctOptionIndex: 1,
    },
    {
      id: 84,
      text: "What is the primary source of Factor III (Thromboplastin) during an injury?",
      options: [
        "Synthesized directly in the liver",
        "Secreted by intact endothelial cells",
        "Secreted from damaged tissue cells or broken platelets",
        "Activated spontaneously in the blood plasma",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 85,
      text: "What is the specific function of Factor XII (Hageman factor)?",
      options: [
        "It converts prothrombin to thrombin directly.",
        "It activates Kallikrein to create Plasmakinin, increasing vessel permeability.",
        "It stabilizes the soft fibrin network into hard, insoluble fibers.",
        "It acts as a primary catalyst for thromboplastin production.",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 86,
      text: "What directly inactivates heparin at an injury site?",
      options: [
        "Release of calcium ions",
        "Contact with air",
        "Activation of prothrombin",
        "Aggregation of white blood cells",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 87,
      text: "Which clotting factors assist thromboplastin and calcium in converting prothrombin to thrombin?",
      options: [
        "V, VII, IX, and X",
        "VII, VIII, IX, and XII",
        "VII, VIII, IX, and X",
        "VIII, IX, X, and XI",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 88,
      text: "Which factor is crucial for stabilizing the fibrin network?",
      options: ["Factor VIII", "Factor X", "Factor XII", "Factor XIII"],
      correctOptionIndex: 3,
    },
    {
      id: 89,
      text: "Which component is present in blood plasma but absent in serum?",
      options: ["Serotonin", "Calcium ions", "Fibrinogen", "Albumin"],
      correctOptionIndex: 2,
    },
    {
      id: 90,
      text: "Why does serum contain a higher concentration of serotonin than plasma?",
      options: [
        "It is synthesized by the liver during bleeding.",
        "It is released by ruptured platelets.",
        "It is secreted by damaged endothelial cells.",
        "It is a byproduct of fibrin degradation.",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 91,
      text: "Which enzyme dissolves the fibrin clot to facilitate tissue repair?",
      options: ["Thrombin", "Plasmin", "Kallikrein", "Thrombokinase"],
      correctOptionIndex: 1,
    },
    {
      id: 92,
      text: "What is the normal blood clotting time in humans?",
      options: ["1-3 minutes", "4-5 minutes", "7-9 minutes", "10-12 minutes"],
      correctOptionIndex: 1,
    },
    {
      id: 93,
      text: "A deficiency in which clotting factors causes Haemophilia?",
      options: [
        "Factors V and VII",
        "Factors VII and X",
        "Factors VIII and IX",
        "Factors XI and XII",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 94,
      text: "Which physical feature of healthy blood vessels prevents thromboplastin production?",
      options: [
        "High elasticity",
        "Smooth inner walls",
        "Thick muscle layers",
        "Semi-permeable membranes",
      ],
      correctOptionIndex: 1,
    },
    {
      id: 95,
      text: "How does normal blood velocity affect intravascular coagulation?",
      options: [
        "High speed inhibits clotting.",
        "High speed accelerates clotting.",
        "Low speed completely prevents clotting.",
        "Blood speed has no effect on clotting.",
      ],
      correctOptionIndex: 0,
    },
    {
      id: 96,
      text: "Which cells secrete the anticoagulant heparin?",
      options: [
        "Neutrophils and macrophages",
        "Lymphocytes and endothelial cells",
        "Basophils and mast cells",
        "Eosinophils and goblet cells",
      ],
      correctOptionIndex: 2,
    },
    {
      id: 97,
      text: "By what exact mechanism does heparin prevent blood clotting?",
      options: [
        "It destroys the fibrin polymer network.",
        "It blocks calcium ions from binding.",
        "It prevents Vitamin K synthesis.",
        "It inhibits prothrombin to thrombin conversion.",
      ],
      correctOptionIndex: 3,
    },
    {
      id: 98,
      text: "Which fluid is directly secreted from a coagulated blood clot?",
      options: ["Cytosol", "Plasma", "Lymph", "Serum"],
      correctOptionIndex: 3,
    },
    {
      id: 99,
      text: "Which fluid lacks the property of coagulation?",
      options: ["Whole blood", "Plasma", "Serum", "Platelet-rich plasma"],
      correctOptionIndex: 2,
    },
    {
      id: 100,
      text: "Which fluid contains a comparatively higher concentration of serotonin?",
      options: ["Plasma", "Intracellular fluid", "Lymph", "Serum"],
      correctOptionIndex: 3,
    },
  ],
};
